# Docker Compose

# version: '3.8'
services:
  self-compassion-rag:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8503:8503"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8503
    volumes:
      - ./logs:/app/logs           # persist monitoring
      - ./data:/app/data           
      - ./processed_documents_clean.json:/app/processed_documents_clean.json
      - ./embeddings.npy:/app/embeddings.npy
      - ./id_index.json:/app/id_index.json
      - ./images:/app/images 
    command: >
      streamlit run streamlit_app.py
      --server.port=8503
      --server.address=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8503/_stcore/health"]
      interval: 15s
      timeout: 5s
      retries: 5